export const ARTICLE_LOAD = 'ARTICLE/LOAD';
export const ARTICLE_LOAD_SUCCESS = 'ARTICLE/LOAD-SUCCESS';
export const ARTICLE_LOAD_ERROR = 'ARTICLE/LOAD-ERROR';
export const ARTICLE_EDIT = 'ARTICLE/EDIT';

export const BASKET_ADD = 'BASKET/ADD';
export const BASKET_REMOVE = 'BASKET/REMOVE';
export const BASKET_CLEAR = 'BASKET/CLEAR';

export const CATALOG_LOAD = 'CATALOG/LOAD';
export const CATALOG_LOAD_SUCCESS = 'CATALOG/LOAD-SUCCESS';
export const CATALOG_LOAD_ERROR = 'CATALOG/LOAD-ERROR';

export const LOGIN_LOGIN_ERROR = 'LOGIN/LOGIN-ERROR';
export const LOGIN_LOGIN_SUCCESS = 'LOGIN/LOGIN-SUCCESS';
export const LOGIN_UNLOGIN = 'LOGIN/UNLOGIN';

export const MODAL_OPEN = 'MODAL/OPEN';
export const MODAL_CLOSE = 'MODAL/CLOSE';